@startuml diagrama_despliegue
' ============================================================================
' DIAGRAMA DE DESPLIEGUE — Gestión Inteligente de Tráfico Urbano
' ============================================================================

title Diagrama de Despliegue — Sistema de Tráfico Urbano

' Estética simplificada y limpia
skinparam nodesep 50
skinparam ranksep 70
skinparam componentStyle rectangle

node "PC1 — Ingesta (192.168.1.100)" as PC1 {
    component "Sensor GPS\n(PUB)" as gps
    component "Sensor Cámara\n(PUB)" as cam
    component "Sensor Espira\n(PUB)" as esp
    
    component "Broker ZMQ\n(XSUB/XPUB)" as proxy
}

node "PC2 — Cerebro y Réplica (192.168.1.101)" as PC2 {
    component "Motor Analítica\n(SUB, PUSH, REP)" as motor
    component "Control Semáforos\n(PULL)" as ctrl
    database "BD Réplica\n(PULL, REP)" as bd_rep
}

node "PC3 — Persistencia (192.168.1.102)" as PC3 {
    database "BD Principal\n(PULL, REP)" as bd_prin
    component "Consola Monitoreo\n(REQ)" as mon
}

' ================================
' ESTRUCTURA CASCADA INVISIBLE
' ================================
' Forzamos a PlantUML a poner PC1 arriba, PC2 en medio y PC3 abajo
PC1 -[hidden]down-> PC2
PC2 -[hidden]down-> PC3

' Colocamos los sensores lado a lado para no alargar PC1
gps -[hidden]right-> cam
cam -[hidden]right-> esp

' ================================
' RELACIONES EXTREMADAMENTE LIMPIAS
' ================================
' Flujos Internos Cortos
gps --> proxy
cam --> proxy
esp --> proxy

motor --> ctrl : " Comando"
motor --> bd_rep : " Backup"

' Cascada de Datos (Caída libre visual)
proxy ---> motor : " Eventos Tráfico"
motor ---> bd_prin : " Datos a Guardar"

' Peticiones de Usuario (Líneas ascendentes/laterales)
motor <--- mon : " Consulta/Alarma"
bd_rep <.. mon : " Failover"
mon -> bd_prin : " Consulta BD"

@enduml
